#include <raylib.h>

#define RAYGUI_IMPLEMENTATION
#define RAYGUI_CUSTOM_ICONS
#include "./resources/images/iconset.h"
#include <raygui.h>

#define NULL_VAL 999
#define NUM_HEADER_OPTIONS 3
#define NUM_WHEEL_OPTIONS 8

// Game
const char *startText = "Press any button on gamepad to begin\n   Click game window to enable music";
const int screenWidth = 800;
const int screenHeight = 600;
const Vector2 center = {screenWidth / 2, screenHeight / 2};
int framesCounter = 0;
Texture2D testTex;
Texture2D grayscaleTestTex;
Music music;

// Wheel header
static const char *headerOptions[NUM_HEADER_OPTIONS] = {"Camera", "Processing", "Tools"};
const Rectangle wheelHeader = {screenWidth / 2 - 150, 25, 300, 75};
int headerSelection = 1;

// Wheel
const int wheelRadius = 225;
const Vector2 wheelCenter = {screenWidth / 2, screenHeight / 2 + 50};
float segmentAngleSpan;
float halfUsedAngleSpan;
static int wheelSelection = NULL_VAL;
static float startAngles[NUM_WHEEL_OPTIONS];
static float endAngles[NUM_WHEEL_OPTIONS];
static Vector2 segmentCenters[NUM_WHEEL_OPTIONS];
unsigned char wheelOptions[NUM_HEADER_OPTIONS][NUM_WHEEL_OPTIONS][NUM_WHEEL_OPTIONS] = {
    {
        {ICON_SINGLE, ICON_BURST, ICON_NONE, ICON_NONE, ICON_NONE, ICON_NONE, ICON_NONE, ICON_NONE},
        {ICON_FLIPX, ICON_NONE, ICON_NONE, ICON_NONE, ICON_NONE, ICON_NONE, ICON_NONE, ICON_NONE},
        {ICON_FLIPY, ICON_NONE, ICON_NONE, ICON_NONE, ICON_NONE, ICON_NONE, ICON_NONE, ICON_NONE},
        {ICON_ROT0, ICON_ROT90, ICON_ROT180, ICON_ROT270, ICON_NONE, ICON_NONE, ICON_NONE, ICON_NONE},
        {ICON_NONE, ICON_NONE, ICON_NONE, ICON_NONE, ICON_NONE, ICON_NONE, ICON_NONE, ICON_NONE},
        {ICON_NONE, ICON_NONE, ICON_NONE, ICON_NONE, ICON_NONE, ICON_NONE, ICON_NONE, ICON_NONE},
        {ICON_NONE, ICON_NONE, ICON_NONE, ICON_NONE, ICON_NONE, ICON_NONE, ICON_NONE, ICON_NONE},
        {ICON_NONE, ICON_NONE, ICON_NONE, ICON_NONE, ICON_NONE, ICON_NONE, ICON_NONE, ICON_NONE},
    },
    {
        {ICON_NONE, ICON_NONE, ICON_NONE, ICON_NONE, ICON_NONE, ICON_NONE, ICON_NONE, ICON_NONE},
        {ICON_NONE, ICON_NONE, ICON_NONE, ICON_NONE, ICON_NONE, ICON_NONE, ICON_NONE, ICON_NONE},
        {ICON_NONE, ICON_NONE, ICON_NONE, ICON_NONE, ICON_NONE, ICON_NONE, ICON_NONE, ICON_NONE},
        {ICON_BLOB, ICON_BLOBTRACK, ICON_NONE, ICON_NONE, ICON_NONE, ICON_NONE, ICON_NONE, ICON_NONE},
        {ICON_FOCUS, ICON_NONE, ICON_NONE, ICON_NONE, ICON_NONE, ICON_NONE, ICON_NONE, ICON_NONE},
        {ICON_NONE, ICON_NONE, ICON_NONE, ICON_NONE, ICON_NONE, ICON_NONE, ICON_NONE, ICON_NONE},
        {ICON_NONE, ICON_NONE, ICON_NONE, ICON_NONE, ICON_NONE, ICON_NONE, ICON_NONE, ICON_NONE},
        {ICON_NONE, ICON_NONE, ICON_NONE, ICON_NONE, ICON_NONE, ICON_NONE, ICON_NONE, ICON_NONE},
    },
    {
        {ICON_AUDIO, ICON_LOWAUDIO, ICON_MUTE, ICON_NONE, ICON_NONE, ICON_NONE, ICON_NONE, ICON_NONE},
        {ICON_HELP, ICON_NONE, ICON_NONE, ICON_NONE, ICON_NONE, ICON_NONE, ICON_NONE, ICON_NONE},
        {ICON_NONE, ICON_NONE, ICON_NONE, ICON_NONE, ICON_NONE, ICON_NONE, ICON_NONE, ICON_NONE},
        {ICON_NONE, ICON_NONE, ICON_NONE, ICON_NONE, ICON_NONE, ICON_NONE, ICON_NONE, ICON_NONE},
        {ICON_NONE, ICON_NONE, ICON_NONE, ICON_NONE, ICON_NONE, ICON_NONE, ICON_NONE, ICON_NONE},
        {ICON_NONE, ICON_NONE, ICON_NONE, ICON_NONE, ICON_NONE, ICON_NONE, ICON_NONE, ICON_NONE},
        {ICON_NONE, ICON_NONE, ICON_NONE, ICON_NONE, ICON_NONE, ICON_NONE, ICON_NONE, ICON_NONE},
        {ICON_NONE, ICON_NONE, ICON_NONE, ICON_NONE, ICON_NONE, ICON_NONE, ICON_NONE, ICON_NONE},
    }};
Color wheelOptionColors[NUM_HEADER_OPTIONS][NUM_WHEEL_OPTIONS][NUM_WHEEL_OPTIONS] = {
    {
        {WHITE, WHITE, WHITE, WHITE, WHITE, WHITE, WHITE, WHITE},
        {WHITE, WHITE, WHITE, WHITE, WHITE, WHITE, WHITE, WHITE},
        {WHITE, WHITE, WHITE, WHITE, WHITE, WHITE, WHITE, WHITE},
        {WHITE, WHITE, WHITE, WHITE, WHITE, WHITE, WHITE, WHITE},
        {WHITE, WHITE, WHITE, WHITE, WHITE, WHITE, WHITE, WHITE},
        {WHITE, WHITE, WHITE, WHITE, WHITE, WHITE, WHITE, WHITE},
        {WHITE, WHITE, WHITE, WHITE, WHITE, WHITE, WHITE, WHITE},
        {WHITE, WHITE, WHITE, WHITE, WHITE, WHITE, WHITE, WHITE},
    },
    {
        {WHITE, WHITE, WHITE, WHITE, WHITE, WHITE, WHITE, WHITE},
        {WHITE, WHITE, WHITE, WHITE, WHITE, WHITE, WHITE, WHITE},
        {WHITE, WHITE, WHITE, WHITE, WHITE, WHITE, WHITE, WHITE},
        {WHITE, WHITE, WHITE, WHITE, WHITE, WHITE, WHITE, WHITE},
        {WHITE, WHITE, WHITE, WHITE, WHITE, WHITE, WHITE, WHITE},
        {WHITE, WHITE, WHITE, WHITE, WHITE, WHITE, WHITE, WHITE},
        {WHITE, WHITE, WHITE, WHITE, WHITE, WHITE, WHITE, WHITE},
        {WHITE, WHITE, WHITE, WHITE, WHITE, WHITE, WHITE, WHITE},
    },
    {
        {GREEN, YELLOW, RED, WHITE, WHITE, WHITE, WHITE, WHITE},
        {WHITE, WHITE, WHITE, WHITE, WHITE, WHITE, WHITE, WHITE},
        {WHITE, WHITE, WHITE, WHITE, WHITE, WHITE, WHITE, WHITE},
        {WHITE, WHITE, WHITE, WHITE, WHITE, WHITE, WHITE, WHITE},
        {WHITE, WHITE, WHITE, WHITE, WHITE, WHITE, WHITE, WHITE},
        {WHITE, WHITE, WHITE, WHITE, WHITE, WHITE, WHITE, WHITE},
        {WHITE, WHITE, WHITE, WHITE, WHITE, WHITE, WHITE, WHITE},
        {WHITE, WHITE, WHITE, WHITE, WHITE, WHITE, WHITE, WHITE},
    }};
int selectedWheelOptions[NUM_HEADER_OPTIONS][NUM_WHEEL_OPTIONS] = {{0, 0, 0, 0, 0, 0, 0, 0}, {0, 0, 0, 0, 0, 0, 0, 0}, {0, 0, 0, 0, 0, 0, 0, 0}};

// Tools
char toolStrings[256][12] = {
    "NULL",
    "Audio On",
    "Audio 50%",
    "Audio Off",
    "Single Shot",
    "Burst",
    "Flip X",
    "Flip Y",
    "Rotate 0",
    "Rotate 90",
    "Rotate 180",
    "Rotate 270",
    "Blob Detect",
    "Blob Track",
    "Focus Value",
    "Help"};